### ISSUE TITLE
Tags are missing

### ISSUE THREAD

**Issue by jvtrigueros** [jiyinyiyong/three.js#1]
As per the [bower-spec](https://github.com/bower/bower.json-spec#version), the version of the bower package version is gotten from the tags. Currently, if you do `bower install --save three.js`, you end up with:

``` json
"dependencies": {
"three.js": "*"
}
```

This isn't very descriptive as to what version of `three.js` I have just installed.

**Comment by tiye** [comment]
Just pushed a tag: https://github.com/jiyinyiyong/three.js/releases

``` js
  "dependencies": {
    "three.js": "~0.70.0"
  }
```

check it out

**Comment by jvtrigueros** [comment]
Perfect!
