### ISSUE TITLE
Include js in examples/js 

### ISSUE THREAD

**Issue by the-reality-engineer** [jiyinyiyong/three.js#2]
Lots of useful things in there.

**Comment by tiye** [comment]
@speigg the only purpose of this repo is to get a minimized package that people may download with bower, since the official package is far too large. So you should refer to official repo if you want.

**Comment by the-reality-engineer** [comment]
You can include more than one file in a bower package. I thought the point of this repo was to avoid the large download size.

**Comment by tiye** [comment]
@speigg a better idea is to register another bower package with `examples/` just as you like. I'm not going to update this repo for other purpose.
