### ISSUE TITLE
0.72 release

### ISSUE THREAD

**Issue by DontRelaX** [jiyinyiyong/three.js#3]
Hey, 
three.js released 72 version https://github.com/mrdoob/three.js/tree/r72
Can you add it or I should make PR?
Thanks

**Comment by tiye** [comment]
https://github.com/jiyinyiyong/three.js/commits/master
https://github.com/jiyinyiyong/three.js/releases/tag/0.72.0
just updated, can you confirm that please?

**Comment by DontRelaX** [comment]
Its work, thanks for quick response!
