### ISSUE TITLE
New version available

### ISSUE THREAD

**Issue by karimbeyrouti** [jiyinyiyong/three.js#6]
Would much prefer using NPM - this project (sadly) needs bower .

**Comment by tiye** [comment]
Would you like to send a PR? I haven't been touching threejs for long.

**Comment by karimbeyrouti** [comment]
Totally will do... :-)

**Comment by karimbeyrouti** [comment]
done: [Pull request: update to version 0.75](https://github.com/jiyinyiyong/three.js/pull/7)

thank you
